image:
  file: .gitpod/Dockerfile

ports:
  - port: 8080
    visibility: public
    onOpen: notify

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - EditorConfig.EditorConfig
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-spring-boot-dashboard
    - Pivotal.vscode-boot-dev-pack
    - Pivotal.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-java-test
    - rangav.vscode-thunder-client
